//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatriculaWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public ALUMNO()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
        }
    
        public string IDALUMNO { get; set; }
        public string NRODOC { get; set; }
        public string NOMBRES { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
    
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
    }
}
