//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatriculaWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.VACANTES = new HashSet<VACANTES>();
            this.MATRICULA = new HashSet<MATRICULA>();
        }
    
        public string IDCURSO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> CREDITOS { get; set; }
        public Nullable<decimal> VACANTES_DISPONIBLES { get; set; }
        public Nullable<decimal> VACANTES_USADAS { get; set; }
        public string IDSECCION { get; set; }
    
        public virtual SECCION SECCION { get; set; }
        public virtual ICollection<VACANTES> VACANTES { get; set; }
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
    }
}
