//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatriculaWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        public string IDMATRICULA { get; set; }
        public string IDALUMNO { get; set; }
        public string IDCURSO { get; set; }
        public string IDSECCION { get; set; }
        public Nullable<System.DateTime> FECHA_MATRICULA { get; set; }
        public Nullable<System.DateTime> FECHA_ANULACION { get; set; }
        public string TIPO_MATRICULA { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
        public virtual CURSO CURSO { get; set; }
        public virtual SECCION SECCION { get; set; }
    }
}
