//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatriculaWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECCION
    {
        public SECCION()
        {
            this.CURSO = new HashSet<CURSO>();
            this.MATRICULA = new HashSet<MATRICULA>();
            this.VACANTES = new HashSet<VACANTES>();
        }
    
        public string IDSECCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<CURSO> CURSO { get; set; }
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        public virtual ICollection<VACANTES> VACANTES { get; set; }
    }
}
